server:
  port: 8081

spring:
  datasource:
    sql-script-encoding: utf-8
    platform: postgres
    url: jdbc:postgresql://192.168.117.131:5432/postgres
    #url: jdbc:postgresql://192.168.0.9:5432/postgres
    username: postgres
    password: 930324
  servlet:
    multipart:
      maxFileSize: 1GB
      maxRequestSize: 1GB

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true